language: go
go:
  - 1.5.1
env:
  - GO15VENDOREXPERIMENT=1
branches:
  only:
    - master
cache:
  directories:
    - $GOPATH/src/github.com/deis/etcd/vendor
services:
  - docker
sudo: required
before_install:
  - wget "https://github.com/Masterminds/glide/releases/download/0.8.1/glide-0.8.1-linux-amd64.tar.gz"
  - sudo tar -vxz -C /usr/local/bin --strip=1 -f glide-0.8.1-linux-amd64.tar.gz
install:
  - GLIDE_HOME=/home/travis/.glide make bootstrap
script:
  - make test
deploy:
  skip_cleanup: true
  provider: script
  script: _scripts/deploy.sh
  on:
    branch: master
